nk_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    '::home.html.twig'

nk_folder:
    resource: "@nkFolderBundle/Resources/config/routing.yml"
    prefix:   /folders

nk_exam:
    resource: "@nkExamBundle/Resources/config/routing.yml"
    prefix:   /exam

nk_document:
    resource: "@nkDocumentBundle/Resources/config/routing.yml"
    prefix:   /

nk_user:
    resource: "@nkUserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile